---

- name: get jira
  command: git config --add user.gitlab {{gitlab_url}}
  args:
    chdir: "{{git_dir}}"

- name: set jira url
  command: git config --add user.jira {{jira_url}}
  args:
    chdir: "{{git_dir}}"

- name: install githook for jira
  become: yes
  become_method: sudo
  command: pip install git+https://github.com/votum/githook_for_jira.git

- name: copy githook to {{git_dir}}
  copy:
    src: files/post-commit
    dest: "{{git_dir}}/.git/hooks/post-commit"
    mode: 0755
