---
- name: install pip
  become: yes
  become_method: sudo
  package: name=python-pip state=latest

- name: unset gitlab url
  command: "git config --unset-all user.gitlab"
  args:
    chdir: "{{git_dir}}"
  ignore_errors: yes

- name: set gitlab url
  command: git config --add user.gitlab {{gitlab_url}}
  args:
    chdir: "{{git_dir}}"

- name: unset jira url
  command: "git config --unset-all user.jira"
  args:
    chdir: "{{git_dir}}"
  ignore_errors: yes

- name: set jira url
  command: git config --add user.jira {{jira_url}}
  args:
    chdir: "{{git_dir}}"

- name: install githook for jira
  become: yes
  become_method: sudo
  command: pip install git+https://github.com/votum/githook-for-jira.git --upgrade

- name: copy githook to {{git_dir}}
  copy:
    src: files/pre-push
    dest: "{{git_dir}}/.git/hooks/pre-push"
    mode: 0755

